version: '2'

services:
  splash:
    image: scrapinghub/splash:3.5.0
    hostname: splash
    command: --maxrss 2048 --max-timeout 300 --disable-lua-sandbox --verbosity 1
    ports:
      - "8051:8050"
    restart: always
  salaries-scraper:
    build: .
    restart: "no"
    command: bash -c "/usr/src/app/wait-for-it.sh --timeout=0 splash:8050 && /usr/src/app/start.sh"
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./:/usr/src/app
      - /dev/shm:/dev/shm