version: '2'

services:
  browser:
    image: browserless/chrome:1-chrome-stable
    volumes:
      - /dev/shm:/dev/shm # Shared memory is required for Chrome to work correctly
    ports:
      - 3000:3000 # Map container port 3000 to host port 3000
    environment:
      - "DEBUG=browserless*"
      - "CONNECTION_TIMEOUT=60000" # Optional: set the connection timeout to 60 seconds

  salaries-scraper:
    build: .
    restart: "no"
    # command: bash -c "/usr/src/app/wait-for-it.sh --timeout=0 localhost:9000 && /usr/src/app/start.sh"
    command: bash -c "/usr/src/app/scraper/start.sh"
    volumes:
      - ./:/usr/src/app/scraper
      - /dev/shm:/dev/shm
    network_mode: "service:browser" # necessary to connect between two containers, without it it wont work and return error 111
